name: Autogen PDFs
on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          conda install python=3.7
          python -m pip install -e .
          python -m pip install markdown xhtml2pdf
      
      - name: Generate Documentation
        run: |
          python makePDFs.py
          git add .
          git commit -m "Automated PDFs Update" -a || true
          git push -f
